name: Release

on:
  release:
    types: [created]

jobs:
    Release:
        name: Release
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        steps:
            - uses: actions/checkout@v2
            - name: Build
              run: cargo build --release --locked
            - name: Upload binaries to release
              uses: svenstaro/upload-release-action@v2
              with:
                repo_token: ${{ secrets.GITHUB_TOKEN }}
                file: target/release/idseq-dedup${{ matrix.os == 'windows-latest' && '.exe' || '' }}
                asset_name: idseq-dedup-${{ runner.os }}
                tag: ${{ github.ref }}
                overwrite: true
