name: Rust

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Check
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly
        override: true
    - uses: actions-rs/cargo@v1
      with:
        command: test
      env:
        CARGO_INCREMENTAL: '0'
        RUSTFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
        RUSTDOCFLAGS: '-Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
    - uses: actions-rs/grcov@v0.1
      if: ${{ !startsWith(github.ref, 'refs/tag') }}
    - uses: codecov/codecov-action@v1

  release:
    name: Release
    runs-on: ${{ matrix.os }}
    if: ${{ startsWith(github.ref, 'refs/tag') }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --locked
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: target/release/idseq-dedup${{ matrix.os == 'windows-latest' && '.exe' || '' }}
        asset_name: idseq-dedup-${{ runner.os }}
        tag: ${{ github.ref }}
        overwrite: true

